name: ros-openimu
on:
  push:
    branches:
      - main
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.3.1
        with:
          command: roslaunch ros_openimu openimu_driver.launch
          base-image: rwthika/ros:noetic-ros-core
          additional-pip-file: docker/additional-pip-files/imu-requirements.txt
          ros-distro: noetic
          platform: amd64
      - name: Clean up
        run: |
          docker system prune -a -f